name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "feature/task2/saranya" ]
  pull_request:
  
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Setup Minikube
        uses: medyagh/setup-minikube@master
        with:
          driver: docker

      - name: Build Docker image inside Minikube
        run: |
          eval $(minikube docker-env)
          docker build -t nodejs-cicd:latest .

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify rollout
        run: kubectl rollout status deployment/nodejs-app --timeout=60s

      - name: Rollback if failed
        if: failure()
        run: bash k8s/rollback.sh
